### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by rzb** [GuillaumeLeclerc/vue-google-maps#128]
I'm on vue 2.2.4. Running `npm install vue-google-maps --save-dev` brings up:

```
npm WARN vue-google-maps@0.1.21 requires a peer of vue@^1.0.0 but none was installed.
npm WARN vue-google-maps@0.1.21 requires a peer of q@^1.4.1 but none was installed.
```

**Comment by Tinoooo** [comment]
If you want to use vue-google-maps with Vue 2 you should use vue2-google-maps.

**Comment by rzb** [comment]
@Tinoooo are you referring to [this 1 star repo](https://github.com/sebastianwos/vue2-google-maps) or is there a more popular one elsewhere?

**Comment by Tinoooo** [comment]
@rzb I'm not quite sure. There are different forks. See https://github.com/GuillaumeLeclerc/vue-google-maps/issues/119

**Comment by pjavanjal** [comment]
Vue-google-map and Vue2-google-map not working with NUXT 
"UNMET PEER DEPENDENCY" error got at the time of installation 

Nuxt.js Error:
ReferenceError: window is not defined
at Object. (/vue-google-maps/index.js:1:6551)
at e (/vue-google-maps/index.js:1:321)
at Object. (/vue-google-maps/index.js:1:689)
at e (/vue-google-maps/index.js:1:321)
at t.__esModule.default (/vue-google-maps/index.js:1:394)
at 6.server-bundle.js:4024:382
at exports.modules.917.r.(anonymous function).exports (/vue-google-maps/index.js:1:15)
at Object.917 (~/vue-google-maps/index.js:1:204)
at webpack_require (webpack:/webpack/bootstrap 42a7e2d4e5d34af8ad2b:25:0)
at Object.349 (6.server-bundle.js:310:74)

**Comment by xkjyeah** [comment]
https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#-getting-started-with-nuxtjs
